# Generated by Django 3.2.3 on 2025-07-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_delete_subscription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoriterecipe',
            unique_together=set(),
        ),
    ]
