# Generated by Django 3.2.25 on 2025-08-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20250828_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(default=1, max_length=20, verbose_name='Название единицы измерения'),
            preserve_default=False,
        ),
    ]
