# Generated by Django 3.2.25 on 2025-08-28 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipeingredient_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='unit',
        ),
    ]
