# Generated by Django 3.2.25 on 2025-08-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipeingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(default='г.', max_length=20, verbose_name='Название единицы измерения'),
        ),
    ]
