# Generated by Django 3.2.25 on 2025-08-11 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_rename_quantity_recipeingredient_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='amount',
            new_name='quantity',
        ),
    ]
