# Generated by Django 3.2.25 on 2025-08-12 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_rename_quantity_recipeingredient_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
