# Generated by Django 3.2.25 on 2025-08-12 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_rename_ingredient_recipeingredient_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingredients',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='amount',
            new_name='quantity',
        ),
    ]
