# Generated by Django 3.2.25 on 2025-08-12 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_auto_20250812_0601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='quantity',
            new_name='amount',
        ),
    ]
