# Generated by Django 3.2.25 on 2025-08-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_rename_quantity_recipeingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
