# Generated by Django 3.2.25 on 2025-08-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20250702_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='foodgram/images/'),
        ),
    ]
